# Generated by Django 6.0.1 on 2026-01-25 04:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('produtor', 'Produtor Rual'), ('empresa', 'Comprador'), ('auditor', 'Administrador')], default='produtor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='O grupo ao qual esse usuário pertence', related_name='costumuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissão específica para esse usuário', related_name='costumuser_set', to='auth.permission', verbose_name='user permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('telefon', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, help_text='Breve descrição sobre o produtor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produtor_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_estoque', models.CharField(blank=True, max_length=10, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
            options={
                'db_table': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Certificacoes',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=8)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('matricula', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=80)),
                ('conteudo_gerado', models.TextField(blank=True, null=True)),
                ('data_geracao', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos')),
            ],
            options={
                'db_table': 'Marketplace',
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuarios'),
        ),
        migrations.CreateModel(
            name='Certificacoes',
            fields=[
                ('id_certificacao', models.AutoField(primary_key=True, serialize=False)),
                ('texto_autodeclaracao', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(max_length=255, upload_to='certificacoes/')),
                ('status_certificacao', models.CharField(blank=True, max_length=9, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos')),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuarios')),
            ],
            options={
                'db_table': 'Certificacoes',
            },
        ),
    ]
