# Generated by Django 6.0.1 on 2026-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='comprovante_endereco',
            field=models.FileField(blank=True, help_text='Comprovante de Endereço', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='contrato_social',
            field=models.FileField(blank=True, help_text='Contrato Social ou Estatuto', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='data_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='documento_cnpj',
            field=models.FileField(blank=True, help_text='Cartão CNPJ ou Certidão Simplificada', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Empresa verificada pela administração'),
        ),
    ]
